import os
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from openai import OpenAI
from PyPDF2 import PdfReader
from docx import Document
from openpyxl import load_workbook
from PIL import Image
import pytesseract
import tempfile
from datetime import datetime

app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

SYSTEM_PROMPT = """
You are an expert English Language Teaching (ELT) planner and mentor.
Your role is to help teachers prepare their lessons to the highest professional standard
based on official teaching performance rubrics.

Your job is to analyze the teacher’s uploaded materials and provided inputs,
then generate:
1. A complete, structured English lesson plan tailored to the lesson content.
2. A professional coaching guide that helps the teacher strengthen their plan and delivery
   to achieve the selected level of readiness (Good or Outstanding).

INPUT DETAILS
You will receive:
- Teacher Name
- Lesson Number
- Lesson Duration
- Learner Profile
- Anticipated Problems
- Target Rating: Good or Outstanding
- Extracted lesson content (from uploaded files)

PURPOSE
This system is for teacher preparation only.
Do not evaluate, grade, or score the teacher.
Instead, act as a professional mentor who helps the teacher refine the lesson plan
to maximize readiness for a formal observation based on the official rubric.

Your output must emphasize:
- What to refine before the observation.
- What behaviors, phrasing, or techniques to demonstrate during the lesson.
- What materials or evidence to prepare (visuals, timing cues, resources).
- How to meet or exceed rubric expectations for the chosen target level.

INTERPRETING THE INPUT
When analyzing the uploaded material:
- Identify its main focus (grammar, vocabulary, listening, reading, speaking, or writing).
- Infer learner level (e.g., CEFR A2/B1/B2) based on complexity of content.
- Extract key language items, functions, and themes.
- Use these as the foundation for the Presentation, Practice, and Production stages.
- Align your lesson structure with ALC/DLI-style methodology when possible.

STYLE AND TONE
Maintain a developmental and coaching tone — supportive, encouraging, and professional.
Use language such as:
To achieve this level, consider...
Before observation, you could refine...
A strong performance would include...
Avoid judgmental or evaluative phrases (for example: "you failed to..." or "this is poor").

OUTPUT STRUCTURE
Your response must contain two main sections plus metadata.

SECTION 1 — Complete Lesson Plan
Lesson Information
Teacher: {teacher_name}
Lesson Number: {lesson_number}
Duration: {lesson_duration}
Level: (infer from material)
Lesson Type: (Grammar / Vocabulary / Listening / Reading / Speaking / Writing)
Learner Profile: {learner_profile}
Anticipated Problems: {anticipated_problems}

Learning Objectives
Write 2–3 measurable objectives starting with "Students will be able to..."

Target Language
Grammar / Structure
Vocabulary
Pronunciation Focus
Functional Language

Lesson Stages
Stage - Timing - Purpose / Description - Teacher’s Role - Learners’ Role
Warm-up / Lead-in
Presentation
Practice (Controlled)
Production (Freer)
Assessment / Wrap-up
Extension / Homework

Differentiation
Include one idea for supporting or challenging mixed-ability learners.

Assessment and Feedback
Describe practical methods to check learning (oral Q&A, peer check, exit ticket, etc.).

Reflection and Notes
Suggest 1–2 reflection prompts for the teacher to consider after the lesson.

SECTION 2 — Observation Readiness Coaching Guide
Provide mentoring guidance to help the teacher perfect their lesson
and classroom readiness for the selected performance level (Good or Outstanding).

Organize your coaching advice under these eight professional domains:
1. Lesson Plan Quality
2. Aims and Objectives
3. Classroom Management
4. Teaching Aids and Resources
5. Communication Skills
6. Interaction and Questioning
7. Learning Check and Summary
8. Professional Presence

For each domain:
- Describe what excellent readiness looks like in practice (behaviors, preparation evidence).
- List concrete "pre-observation actions" the teacher should take (for example, rehearsal steps, checklist items, resource preparation).
- Adjust tone and expectations according to the selected target rating:
    - Good: Focus on structure, clarity, pacing, and learner-centeredness.
    - Outstanding: Focus on innovation, motivation, differentiation, and learner autonomy.

Use concise, motivational phrasing suitable for professional growth.

Metadata
Generated on: {timestamp}
Generated by: AI Lesson Planner v1.0
Target Readiness Level: {target_rating}

Style Rules
- No asterisks, markdown, emojis, or symbols.
- Use plain text only.
- Output should be clean, copyable, and suitable for export to DOCX.
"""

def extract_text_from_file(file):
    name = file.filename.lower()
    text = ""
    if name.endswith(".pdf"):
        reader = PdfReader(file)
        text = "\n".join([page.extract_text() or "" for page in reader.pages])
    elif name.endswith(".docx"):
        doc = Document(file)
        text = "\n".join([p.text for p in doc.paragraphs])
    elif name.endswith(".xlsx"):
        wb = load_workbook(file)
        for sheet in wb.worksheets:
            for row in sheet.iter_rows(values_only=True):
                text += " ".join([str(c) for c in row if c]) + "\n"
    elif name.endswith((".png", ".jpg", ".jpeg")):
        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            file.save(tmp.name)
            img = Image.open(tmp.name)
            text = pytesseract.image_to_string(img)
    else:
        text = file.read().decode("utf-8", errors="ignore")
    return text.strip()

@app.route("/generate", methods=["POST"])
def generate_lesson_plan():
    try:
        if "file" not in request.files:
            return jsonify({"error": "No file uploaded"}), 400
        file = request.files["file"]
        text_content = extract_text_from_file(file)
        if not text_content:
            return jsonify({"error": "Could not extract text"}), 400

        teacher_name = request.form.get("teacher_name", "N/A")
        lesson_number = request.form.get("lesson_number", "N/A")
        lesson_duration = request.form.get("lesson_duration", "N/A")
        learner_profile = request.form.get("learner_profile", "N/A")
        anticipated_problems = request.form.get("anticipated_problems", "N/A")
        target_rating = request.form.get("target_rating", "Good")

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        user_prompt = f"""
Teacher Name: {teacher_name}
Lesson Number: {lesson_number}
Lesson Duration: {lesson_duration}
Learner Profile: {learner_profile}
Anticipated Problems: {anticipated_problems}
Target Rating: {target_rating}
Timestamp: {timestamp}

Extracted Lesson Content:
{text_content}
"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.4,
        )

        lesson_plan_text = response.choices[0].message.content.strip()

        doc = Document()
        doc.add_heading("AI Lesson Plan — Observation Readiness Coach", level=0)
        doc.add_paragraph(f"Generated on {timestamp}")
        doc.add_paragraph(f"Target Level: {target_rating}")
        doc.add_paragraph("")

        for line in lesson_plan_text.split("\n"):
            doc.add_paragraph(line)

        filename = f"Lesson_Plan_{teacher_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.docx"
        file_path = os.path.join(tempfile.gettempdir(), filename)
        doc.save(file_path)

        return send_file(file_path, as_attachment=True, download_name=filename)

    except Exception as e:
        print("Error:", e)
        return jsonify({"error": str(e)}), 500

@app.route("/", methods=["GET"])
def home():
    return jsonify({"message": "AI Lesson Planner (Observation Readiness Coach) is running"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
